const itemData = [
  {
    name: "WishList 1",
    tags: ["디젤피카부", "태그길게길게넘치나안넘치나테스트"],
    imgSrc: "./img/disel.jpg",
    imgAlt: "디젤-반팔티",
    category: "CLOTHES",
  },
  {
    name: "WishList 2",
    tags: ["가젤볼드핑크글로우", "사고싶은데못구하는거"],
    imgSrc: "./img/addidas.jpg",
    imgAlt: "아디다스-신발",
    category: "SHOES",
  },
  {
    name: "WishList 3",
    tags: ["마뗑킴가방", "실내화주머니"],
    imgSrc: "./img/matinkim.jpg",
    imgAlt: "마뗑킴-가방",
    category: "ETC",
  },
  {
    name: "WishList 4",
    tags: ["카시나", "덩크"],
    imgSrc: "./img/kasina.jpg",
    imgAlt: "카시나-신발",
    category: "SHOES",
  },
  {
    name: "WishList 5",
    tags: ["aeae모자", "재입고해주세요"],
    imgSrc: "./img/aeae.jpg",
    imgAlt: "aeae-모자",
    category: "ETC",
  },
  {
    name: "WishList 6",
    tags: ["덩크남고래", "범고래는질려요"],
    imgSrc: "./img/nike.jpg",
    imgAlt: "나이키-덩크",
    category: "SHOES",
  },
  {
    name: "WishList 7",
    tags: ["베아니트탑", "비비안웨스트우드🫶🏻"],
    imgSrc: "./img/vivien.jpg",
    imgAlt: "비비안웨스트우드-니트탑",
    category: "CLOTHES",
  },
  {
    name: "WishList 8",
    tags: ["킨재스퍼락", "예쁘지만안어울릴듯"],
    imgSrc: "./img/keen.jpg",
    imgAlt: "킨-신발",
    category: "SHOES",
  },
  {
    name: "WishList 9",
    tags: ["포터탱커가방", "일본에서사올걸"],
    imgSrc: "./img/poter.jp",
    imgAlt: "포터-가방",
    category: "ETC",
  },
];
